/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.getfit;

import com.mycompany.getfit.classlist.*;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author eric_
 */
public class gui extends javax.swing.JFrame {
  
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Splash = new javax.swing.JPanel();
        Splash_Title = new javax.swing.JLabel();
        Splash_ProgressBar = new javax.swing.JProgressBar();
        Onboarding = new javax.swing.JPanel();
        Onboard_Info = new javax.swing.JPanel();
        Onboard_Info1 = new javax.swing.JPanel();
        Onboard_Info1_Picture = new javax.swing.JPanel();
        Onboard_Info1_Header = new javax.swing.JLabel();
        Onboard_Info1_Text1 = new javax.swing.JLabel();
        Onboard_Info1_Text2 = new javax.swing.JLabel();
        Onboard_Info2 = new javax.swing.JPanel();
        Onboard_Info2_Picture = new javax.swing.JPanel();
        Onboard_Info2_Header = new javax.swing.JLabel();
        Onboard_Info2_Text1 = new javax.swing.JLabel();
        Onboard_Info2_Text2 = new javax.swing.JLabel();
        Onboard_Info3 = new javax.swing.JPanel();
        Onboard_Info3_Picture = new javax.swing.JPanel();
        Onboard_Info3_Header = new javax.swing.JLabel();
        Onboard_Info3_Text1 = new javax.swing.JLabel();
        Onboard_Info3_Text2 = new javax.swing.JLabel();
        Onboard_BtnNext = new javax.swing.JButton();
        Login_Background = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        Login_Header = new javax.swing.JLabel();
        Login_Panel = new javax.swing.JPanel();
        Login_email = new javax.swing.JTextPane();
        Login_password = new javax.swing.JPasswordField();
        Login_extra = new javax.swing.JPanel();
        Login_radio = new javax.swing.JRadioButton();
        Login_text1 = new javax.swing.JLabel();
        Login_BtnSubmit = new javax.swing.JButton();
        Login_Line1 = new javax.swing.JPanel();
        Login_text2 = new javax.swing.JLabel();
        Login_Gmail = new javax.swing.JPanel();
        Login_Facebook = new javax.swing.JPanel();
        Login_Twitter = new javax.swing.JPanel();
        Login_Text1 = new javax.swing.JLabel();
        Login_Text2 = new javax.swing.JLabel();
        MainScreen = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        Sidebar_Header = new javax.swing.JLabel();
        Sidebar_List = new javax.swing.JPanel();
        Sidebar_Home = new javax.swing.JPanel();
        Home_Status = new javax.swing.JPanel();
        Home_Icon = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        Sidebar_Plan = new javax.swing.JPanel();
        Plan_Status = new javax.swing.JPanel();
        Plan_Icon = new javax.swing.JPanel();
        BtnPlan = new javax.swing.JButton();
        Sidebar_Stat = new javax.swing.JPanel();
        Stat_Status = new javax.swing.JPanel();
        Stat_Icon = new javax.swing.JPanel();
        BtnStat = new javax.swing.JButton();
        Sidebar_Profile = new javax.swing.JPanel();
        Profile_Status = new javax.swing.JPanel();
        Profile_Icon = new javax.swing.JPanel();
        BtnProfile = new javax.swing.JButton();
        Sidebar_Nutrionist = new javax.swing.JPanel();
        Add_Status = new javax.swing.JPanel();
        Add_Icon = new javax.swing.JPanel();
        BtnAdd = new javax.swing.JButton();
        MainCardPane = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        Home_Text1 = new javax.swing.JLabel();
        Home_Text2 = new javax.swing.JLabel();
        Home_Info1 = new javax.swing.JPanel();
        Home_Icon1 = new javax.swing.JPanel();
        Home_Icon1_Text1 = new javax.swing.JLabel();
        Home_Icon1_Text2 = new javax.swing.JLabel();
        Home_Info1_Text1 = new javax.swing.JLabel();
        Home_Info1_Text2 = new javax.swing.JLabel();
        Home_Info1_Text3 = new javax.swing.JLabel();
        Home_Info2 = new javax.swing.JPanel();
        Home_Icon2 = new javax.swing.JPanel();
        Home_Icon2_Text1 = new javax.swing.JLabel();
        Home_Icon2_Text2 = new javax.swing.JLabel();
        Home_Info2_Text1 = new javax.swing.JLabel();
        Home_Info2_Text2 = new javax.swing.JLabel();
        Home_Info2_Text3 = new javax.swing.JLabel();
        Plan = new javax.swing.JPanel();
        Plan_HeaderBackground = new javax.swing.JPanel();
        Plan_BtnDay1 = new javax.swing.JButton();
        Plan_BtnDay2 = new javax.swing.JButton();
        Plan_BtnDay3 = new javax.swing.JButton();
        Plan_BtnDay4 = new javax.swing.JButton();
        Plan_BtnDay5 = new javax.swing.JButton();
        Plan_BtnDay6 = new javax.swing.JButton();
        Plan_CardPane = new javax.swing.JPanel();
        Plan_GridPane = new javax.swing.JPanel();
        Breakfast = new javax.swing.JPanel();
        Breakfast_Header = new javax.swing.JLabel();
        Breakfast_Carbo = new javax.swing.JPanel();
        Breakfast_Carbo_Line = new javax.swing.JPanel();
        Brreakfast_Carbo_Header = new javax.swing.JLabel();
        Breakfast_Carbo_FoodName = new javax.swing.JLabel();
        Breakfast_Vegie = new javax.swing.JPanel();
        Breakfast_Vegie_Line = new javax.swing.JPanel();
        Brreakfast_Vegie_Header = new javax.swing.JLabel();
        Breakfast_Vegie_FoodName = new javax.swing.JLabel();
        Breakfast_Protein = new javax.swing.JPanel();
        Breakfast_Protein_Line = new javax.swing.JPanel();
        Brreakfast_Protein_Header = new javax.swing.JLabel();
        Breakfast_Protein_FoodName = new javax.swing.JLabel();
        Lunch = new javax.swing.JPanel();
        Lunch_Header = new javax.swing.JLabel();
        Lunch_Carbo = new javax.swing.JPanel();
        Lunch_Carbo_Line = new javax.swing.JPanel();
        Lunch_Carbo_Header = new javax.swing.JLabel();
        Lunch_Carbo_FoodName = new javax.swing.JLabel();
        Lunch_Vegie = new javax.swing.JPanel();
        Lunch_Vegie_Line = new javax.swing.JPanel();
        Lunch_Vegie_Header = new javax.swing.JLabel();
        Lunch_Vegie_FoodName = new javax.swing.JLabel();
        Breakfast_Protein1 = new javax.swing.JPanel();
        Lunch_Protein_Line = new javax.swing.JPanel();
        Lunch_Protein_Header = new javax.swing.JLabel();
        Lunch_Protein_FoodName = new javax.swing.JLabel();
        Dinner = new javax.swing.JPanel();
        Breakfast_Header2 = new javax.swing.JLabel();
        Dinner_Carbo = new javax.swing.JPanel();
        Dinner_Carbo_Line = new javax.swing.JPanel();
        Dinner_Carbo_Header = new javax.swing.JLabel();
        Dinner_Carbo_FoodName = new javax.swing.JLabel();
        Dinner_Vegie = new javax.swing.JPanel();
        Dinner_Vegie_Line = new javax.swing.JPanel();
        Dinner_Vegie_Header = new javax.swing.JLabel();
        Dinner_Vegie_FoodName = new javax.swing.JLabel();
        Dinner_Protein = new javax.swing.JPanel();
        Dinner_Protein_Line = new javax.swing.JPanel();
        Dinner_Protein_Header = new javax.swing.JLabel();
        Dinner_Protein_FoodName = new javax.swing.JLabel();
        Stat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        Profile_Header = new javax.swing.JLabel();
        Profile_UserPicture = new javax.swing.JLabel();
        ScrollPane1 = new javax.swing.JScrollPane();
        Profile_UserName = new javax.swing.JTextPane();
        Profile_Icon1 = new javax.swing.JLabel();
        Profile_Icon2 = new javax.swing.JLabel();
        Profile_Icon3 = new javax.swing.JLabel();
        Profile_Icon4 = new javax.swing.JLabel();
        Nutrionist = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GetFit Pro");
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setPreferredSize(new java.awt.Dimension(1200, 600));
        background.setLayout(null);

        Splash.setBackground(new java.awt.Color(145, 199, 136));
        Splash.setPreferredSize(new java.awt.Dimension(1200, 600));
        Splash.setLayout(null);

        Splash_Title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Splash_Title.setForeground(new java.awt.Color(255, 255, 255));
        Splash_Title.setText("GetFit");
        Splash.add(Splash_Title);
        Splash_Title.setBounds(532, 268, 135, 67);

        Splash_ProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        Splash_ProgressBar.setForeground(new java.awt.Color(145, 199, 136));
        Splash_ProgressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 199, 136)));
        Splash_ProgressBar.setFocusable(false);
        Splash_ProgressBar.setMinimumSize(new java.awt.Dimension(10, 12));
        Splash_ProgressBar.setRequestFocusEnabled(false);
        Splash_ProgressBar.setVerifyInputWhenFocusTarget(false);
        Splash.add(Splash_ProgressBar);
        Splash_ProgressBar.setBounds(100, 560, 1000, 12);

        background.add(Splash);
        Splash.setBounds(0, 0, 1200, 600);

        Onboarding.setBackground(new java.awt.Color(255, 255, 255));
        Onboarding.setMinimumSize(new java.awt.Dimension(1200, 600));
        Onboarding.setPreferredSize(new java.awt.Dimension(1200, 600));
        Onboarding.setLayout(null);

        Onboard_Info.setBackground(new java.awt.Color(255, 255, 204));
        Onboard_Info.setMinimumSize(new java.awt.Dimension(400, 400));
        Onboard_Info.setPreferredSize(new java.awt.Dimension(400, 400));
        Onboard_Info.setLayout(new javax.swing.OverlayLayout(Onboard_Info));

        Onboard_Info1.setBackground(new java.awt.Color(255, 255, 255));
        Onboard_Info1.setLayout(null);

        Onboard_Info1_Picture.setBackground(new java.awt.Color(204, 255, 255));
        Onboard_Info1_Picture.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout Onboard_Info1_PictureLayout = new javax.swing.GroupLayout(Onboard_Info1_Picture);
        Onboard_Info1_Picture.setLayout(Onboard_Info1_PictureLayout);
        Onboard_Info1_PictureLayout.setHorizontalGroup(
            Onboard_Info1_PictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        Onboard_Info1_PictureLayout.setVerticalGroup(
            Onboard_Info1_PictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        Onboard_Info1.add(Onboard_Info1_Picture);
        Onboard_Info1_Picture.setBounds(70, 20, 260, 250);

        Onboard_Info1_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Onboard_Info1_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info1_Header.setText("1 Month Diet Plan");
        Onboard_Info1.add(Onboard_Info1_Header);
        Onboard_Info1_Header.setBounds(0, 310, 400, 20);

        Onboard_Info1_Text1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Onboard_Info1_Text1.setForeground(new java.awt.Color(102, 102, 102));
        Onboard_Info1_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info1_Text1.setText("you can choose your own diet plan");
        Onboard_Info1.add(Onboard_Info1_Text1);
        Onboard_Info1_Text1.setBounds(0, 340, 400, 30);

        Onboard_Info1_Text2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Onboard_Info1_Text2.setForeground(new java.awt.Color(102, 102, 102));
        Onboard_Info1_Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info1_Text2.setText("according to what you desire");
        Onboard_Info1.add(Onboard_Info1_Text2);
        Onboard_Info1_Text2.setBounds(0, 360, 400, 30);

        Onboard_Info.add(Onboard_Info1);

        Onboard_Info2.setBackground(new java.awt.Color(255, 255, 255));
        Onboard_Info2.setLayout(null);

        Onboard_Info2_Picture.setBackground(new java.awt.Color(204, 255, 255));
        Onboard_Info2_Picture.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout Onboard_Info2_PictureLayout = new javax.swing.GroupLayout(Onboard_Info2_Picture);
        Onboard_Info2_Picture.setLayout(Onboard_Info2_PictureLayout);
        Onboard_Info2_PictureLayout.setHorizontalGroup(
            Onboard_Info2_PictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        Onboard_Info2_PictureLayout.setVerticalGroup(
            Onboard_Info2_PictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        Onboard_Info2.add(Onboard_Info2_Picture);
        Onboard_Info2_Picture.setBounds(70, 20, 260, 250);

        Onboard_Info2_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Onboard_Info2_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info2_Header.setText("Track Your Health");
        Onboard_Info2.add(Onboard_Info2_Header);
        Onboard_Info2_Header.setBounds(0, 310, 390, 20);

        Onboard_Info2_Text1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Onboard_Info2_Text1.setForeground(new java.awt.Color(102, 102, 102));
        Onboard_Info2_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info2_Text1.setText("with our amazing built in tools for");
        Onboard_Info2.add(Onboard_Info2_Text1);
        Onboard_Info2_Text1.setBounds(0, 340, 390, 25);

        Onboard_Info2_Text2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Onboard_Info2_Text2.setForeground(new java.awt.Color(102, 102, 102));
        Onboard_Info2_Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info2_Text2.setText("track your progress");
        Onboard_Info2.add(Onboard_Info2_Text2);
        Onboard_Info2_Text2.setBounds(0, 360, 390, 25);

        Onboard_Info.add(Onboard_Info2);

        Onboard_Info3.setBackground(new java.awt.Color(255, 255, 255));
        Onboard_Info3.setLayout(null);

        Onboard_Info3_Picture.setBackground(new java.awt.Color(204, 255, 255));
        Onboard_Info3_Picture.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout Onboard_Info3_PictureLayout = new javax.swing.GroupLayout(Onboard_Info3_Picture);
        Onboard_Info3_Picture.setLayout(Onboard_Info3_PictureLayout);
        Onboard_Info3_PictureLayout.setHorizontalGroup(
            Onboard_Info3_PictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        Onboard_Info3_PictureLayout.setVerticalGroup(
            Onboard_Info3_PictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        Onboard_Info3.add(Onboard_Info3_Picture);
        Onboard_Info3_Picture.setBounds(70, 20, 260, 250);

        Onboard_Info3_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Onboard_Info3_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info3_Header.setText("Set Your Goal");
        Onboard_Info3.add(Onboard_Info3_Header);
        Onboard_Info3_Header.setBounds(0, 310, 390, 20);

        Onboard_Info3_Text1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Onboard_Info3_Text1.setForeground(new java.awt.Color(102, 102, 102));
        Onboard_Info3_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info3_Text1.setText("dive in and start hitting on your diet");
        Onboard_Info3.add(Onboard_Info3_Text1);
        Onboard_Info3_Text1.setBounds(0, 340, 390, 30);

        Onboard_Info3_Text2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Onboard_Info3_Text2.setForeground(new java.awt.Color(102, 102, 102));
        Onboard_Info3_Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Onboard_Info3_Text2.setText("goals today");
        Onboard_Info3.add(Onboard_Info3_Text2);
        Onboard_Info3_Text2.setBounds(0, 360, 390, 30);

        Onboard_Info.add(Onboard_Info3);

        Onboarding.add(Onboard_Info);
        Onboard_Info.setBounds(400, 60, 400, 400);

        Onboard_BtnNext.setBackground(new java.awt.Color(145, 199, 136));
        Onboard_BtnNext.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Onboard_BtnNext.setForeground(new java.awt.Color(255, 255, 255));
        Onboard_BtnNext.setText("Get Started");
        Onboard_BtnNext.setBorder(null);
        Onboard_BtnNext.setBorderPainted(false);
        Onboard_BtnNext.setFocusPainted(false);
        Onboard_BtnNext.setFocusable(false);
        Onboard_BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Onboard_BtnNextActionPerformed(evt);
            }
        });
        Onboarding.add(Onboard_BtnNext);
        Onboard_BtnNext.setBounds(490, 490, 220, 50);

        background.add(Onboarding);
        Onboarding.setBounds(0, 0, 1200, 600);

        Login_Background.setBackground(new java.awt.Color(255, 255, 255));
        Login_Background.setLayout(null);

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Login.setLayout(null);

        Login_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login_Header.setForeground(new java.awt.Color(145, 199, 136));
        Login_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_Header.setText("Login");
        Login.add(Login_Header);
        Login_Header.setBounds(0, 10, 400, 30);

        Login_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Login_Panel.setLayout(null);

        Login_email.setBackground(new java.awt.Color(229, 241, 227));
        Login_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Login_email.setForeground(new java.awt.Color(178, 178, 178));
        Login_email.setText("e-mail");
        Login_email.setMargin(new java.awt.Insets(5, 15, 5, 6));
        Login_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Login_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Login_emailFocusLost(evt);
            }
        });
        Login_Panel.add(Login_email);
        Login_email.setBounds(50, 10, 290, 35);

        Login_password.setBackground(new java.awt.Color(229, 241, 227));
        Login_password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Login_password.setForeground(new java.awt.Color(178, 178, 178));
        Login_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Login_password.setText("password");
        Login_password.setBorder(null);
        Login_password.setMargin(new java.awt.Insets(5, 15, 5, 6));
        Login_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Login_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Login_passwordFocusLost(evt);
            }
        });
        Login_Panel.add(Login_password);
        Login_password.setBounds(60, 60, 280, 30);

        Login_extra.setBackground(new java.awt.Color(229, 241, 227));

        javax.swing.GroupLayout Login_extraLayout = new javax.swing.GroupLayout(Login_extra);
        Login_extra.setLayout(Login_extraLayout);
        Login_extraLayout.setHorizontalGroup(
            Login_extraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        Login_extraLayout.setVerticalGroup(
            Login_extraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Login_Panel.add(Login_extra);
        Login_extra.setBounds(50, 60, 10, 30);

        Login_radio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_radio.setForeground(new java.awt.Color(178, 178, 178));
        Login_radio.setText("Remember me");
        Login_radio.setContentAreaFilled(false);
        Login_radio.setFocusPainted(false);
        Login_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_radioActionPerformed(evt);
            }
        });
        Login_Panel.add(Login_radio);
        Login_radio.setBounds(50, 120, 130, 21);

        Login_text1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_text1.setForeground(new java.awt.Color(178, 178, 178));
        Login_text1.setText("Forget Password?");
        Login_Panel.add(Login_text1);
        Login_text1.setBounds(220, 120, 120, 20);

        Login_BtnSubmit.setBackground(new java.awt.Color(145, 199, 136));
        Login_BtnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login_BtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        Login_BtnSubmit.setText("Login");
        Login_BtnSubmit.setBorder(null);
        Login_BtnSubmit.setBorderPainted(false);
        Login_BtnSubmit.setFocusPainted(false);
        Login_BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BtnSubmitActionPerformed(evt);
            }
        });
        Login_Panel.add(Login_BtnSubmit);
        Login_BtnSubmit.setBounds(50, 160, 290, 60);

        Login_Line1.setBackground(new java.awt.Color(255, 255, 255));
        Login_Line1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(178, 178, 178)));
        Login_Line1.setLayout(null);

        Login_text2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Login_text2.setForeground(new java.awt.Color(178, 178, 178));
        Login_text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_text2.setText("or");
        Login_Line1.add(Login_text2);
        Login_text2.setBounds(100, 10, 37, 16);

        Login_Panel.add(Login_Line1);
        Login_Line1.setBounds(70, 240, 240, 30);

        Login_Gmail.setBackground(new java.awt.Color(204, 255, 255));
        Login_Gmail.setLayout(null);
        Login_Panel.add(Login_Gmail);
        Login_Gmail.setBounds(110, 280, 40, 40);

        Login_Facebook.setBackground(new java.awt.Color(204, 255, 255));
        Login_Facebook.setLayout(null);
        Login_Panel.add(Login_Facebook);
        Login_Facebook.setBounds(170, 280, 40, 40);

        Login_Twitter.setBackground(new java.awt.Color(204, 255, 255));
        Login_Twitter.setLayout(null);
        Login_Panel.add(Login_Twitter);
        Login_Twitter.setBounds(230, 280, 40, 40);

        Login.add(Login_Panel);
        Login_Panel.setBounds(10, 60, 380, 380);

        Login_Text1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_Text1.setForeground(new java.awt.Color(178, 178, 178));
        Login_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_Text1.setText("Don't have an account?");
        Login.add(Login_Text1);
        Login_Text1.setBounds(70, 460, 170, 20);

        Login_Text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_Text2.setForeground(new java.awt.Color(51, 153, 255));
        Login_Text2.setText("Create one");
        Login.add(Login_Text2);
        Login_Text2.setBounds(240, 460, 80, 20);

        Login_Background.add(Login);
        Login.setBounds(400, 50, 400, 500);

        background.add(Login_Background);
        Login_Background.setBounds(0, 0, 1200, 600);

        MainScreen.setBackground(new java.awt.Color(255, 255, 255));
        MainScreen.setLayout(null);

        Sidebar.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar.setLayout(null);

        Sidebar_Header.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Sidebar_Header.setForeground(new java.awt.Color(255, 255, 255));
        Sidebar_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sidebar_Header.setText("GetFit");
        Sidebar.add(Sidebar_Header);
        Sidebar_Header.setBounds(0, 10, 200, 50);

        Sidebar_List.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar_List.setLayout(null);

        Sidebar_Home.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar_Home.setLayout(null);

        Home_Status.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout Home_StatusLayout = new javax.swing.GroupLayout(Home_Status);
        Home_Status.setLayout(Home_StatusLayout);
        Home_StatusLayout.setHorizontalGroup(
            Home_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        Home_StatusLayout.setVerticalGroup(
            Home_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Home.add(Home_Status);
        Home_Status.setBounds(0, 0, 5, 60);

        Home_Icon.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout Home_IconLayout = new javax.swing.GroupLayout(Home_Icon);
        Home_Icon.setLayout(Home_IconLayout);
        Home_IconLayout.setHorizontalGroup(
            Home_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Home_IconLayout.setVerticalGroup(
            Home_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Home.add(Home_Icon);
        Home_Icon.setBounds(10, 0, 60, 60);

        BtnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnHome.setForeground(new java.awt.Color(255, 255, 255));
        BtnHome.setText("Home");
        BtnHome.setBorder(null);
        BtnHome.setBorderPainted(false);
        BtnHome.setContentAreaFilled(false);
        BtnHome.setFocusPainted(false);
        BtnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        Sidebar_Home.add(BtnHome);
        BtnHome.setBounds(80, 10, 100, 40);

        Sidebar_List.add(Sidebar_Home);
        Sidebar_Home.setBounds(0, 10, 200, 60);

        Sidebar_Plan.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar_Plan.setLayout(null);

        Plan_Status.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Plan_StatusLayout = new javax.swing.GroupLayout(Plan_Status);
        Plan_Status.setLayout(Plan_StatusLayout);
        Plan_StatusLayout.setHorizontalGroup(
            Plan_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        Plan_StatusLayout.setVerticalGroup(
            Plan_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Plan.add(Plan_Status);
        Plan_Status.setBounds(0, 0, 5, 60);

        Plan_Icon.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout Plan_IconLayout = new javax.swing.GroupLayout(Plan_Icon);
        Plan_Icon.setLayout(Plan_IconLayout);
        Plan_IconLayout.setHorizontalGroup(
            Plan_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Plan_IconLayout.setVerticalGroup(
            Plan_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Plan.add(Plan_Icon);
        Plan_Icon.setBounds(10, 0, 60, 60);

        BtnPlan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnPlan.setForeground(new java.awt.Color(255, 255, 255));
        BtnPlan.setText("Plan");
        BtnPlan.setBorder(null);
        BtnPlan.setBorderPainted(false);
        BtnPlan.setContentAreaFilled(false);
        BtnPlan.setFocusPainted(false);
        BtnPlan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlanActionPerformed(evt);
            }
        });
        Sidebar_Plan.add(BtnPlan);
        BtnPlan.setBounds(80, 10, 100, 40);

        Sidebar_List.add(Sidebar_Plan);
        Sidebar_Plan.setBounds(0, 70, 200, 60);

        Sidebar_Stat.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar_Stat.setLayout(null);

        Stat_Status.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Stat_StatusLayout = new javax.swing.GroupLayout(Stat_Status);
        Stat_Status.setLayout(Stat_StatusLayout);
        Stat_StatusLayout.setHorizontalGroup(
            Stat_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        Stat_StatusLayout.setVerticalGroup(
            Stat_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Stat.add(Stat_Status);
        Stat_Status.setBounds(0, 0, 5, 60);

        Stat_Icon.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout Stat_IconLayout = new javax.swing.GroupLayout(Stat_Icon);
        Stat_Icon.setLayout(Stat_IconLayout);
        Stat_IconLayout.setHorizontalGroup(
            Stat_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Stat_IconLayout.setVerticalGroup(
            Stat_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Stat.add(Stat_Icon);
        Stat_Icon.setBounds(10, 0, 60, 60);

        BtnStat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnStat.setForeground(new java.awt.Color(255, 255, 255));
        BtnStat.setText("Progress");
        BtnStat.setBorder(null);
        BtnStat.setBorderPainted(false);
        BtnStat.setContentAreaFilled(false);
        BtnStat.setFocusPainted(false);
        BtnStat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStatActionPerformed(evt);
            }
        });
        Sidebar_Stat.add(BtnStat);
        BtnStat.setBounds(80, 10, 100, 40);

        Sidebar_List.add(Sidebar_Stat);
        Sidebar_Stat.setBounds(0, 130, 200, 60);

        Sidebar_Profile.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar_Profile.setLayout(null);

        Profile_Status.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Profile_StatusLayout = new javax.swing.GroupLayout(Profile_Status);
        Profile_Status.setLayout(Profile_StatusLayout);
        Profile_StatusLayout.setHorizontalGroup(
            Profile_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        Profile_StatusLayout.setVerticalGroup(
            Profile_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Profile.add(Profile_Status);
        Profile_Status.setBounds(0, 0, 5, 60);

        Profile_Icon.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout Profile_IconLayout = new javax.swing.GroupLayout(Profile_Icon);
        Profile_Icon.setLayout(Profile_IconLayout);
        Profile_IconLayout.setHorizontalGroup(
            Profile_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Profile_IconLayout.setVerticalGroup(
            Profile_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Profile.add(Profile_Icon);
        Profile_Icon.setBounds(10, 0, 60, 60);

        BtnProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnProfile.setForeground(new java.awt.Color(255, 255, 255));
        BtnProfile.setText("Profile");
        BtnProfile.setBorder(null);
        BtnProfile.setBorderPainted(false);
        BtnProfile.setContentAreaFilled(false);
        BtnProfile.setFocusPainted(false);
        BtnProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfileActionPerformed(evt);
            }
        });
        Sidebar_Profile.add(BtnProfile);
        BtnProfile.setBounds(80, 10, 100, 40);

        Sidebar_List.add(Sidebar_Profile);
        Sidebar_Profile.setBounds(0, 190, 200, 60);

        Sidebar_Nutrionist.setBackground(new java.awt.Color(145, 199, 136));
        Sidebar_Nutrionist.setLayout(null);

        Add_Status.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Add_StatusLayout = new javax.swing.GroupLayout(Add_Status);
        Add_Status.setLayout(Add_StatusLayout);
        Add_StatusLayout.setHorizontalGroup(
            Add_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        Add_StatusLayout.setVerticalGroup(
            Add_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Nutrionist.add(Add_Status);
        Add_Status.setBounds(0, 0, 5, 60);

        Add_Icon.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout Add_IconLayout = new javax.swing.GroupLayout(Add_Icon);
        Add_Icon.setLayout(Add_IconLayout);
        Add_IconLayout.setHorizontalGroup(
            Add_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        Add_IconLayout.setVerticalGroup(
            Add_IconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Sidebar_Nutrionist.add(Add_Icon);
        Add_Icon.setBounds(10, 0, 60, 60);

        BtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdd.setText("Add");
        BtnAdd.setBorder(null);
        BtnAdd.setBorderPainted(false);
        BtnAdd.setContentAreaFilled(false);
        BtnAdd.setFocusPainted(false);
        BtnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });
        Sidebar_Nutrionist.add(BtnAdd);
        BtnAdd.setBounds(80, 10, 100, 40);

        Sidebar_List.add(Sidebar_Nutrionist);
        Sidebar_Nutrionist.setBounds(0, 250, 200, 60);

        Sidebar.add(Sidebar_List);
        Sidebar_List.setBounds(0, 70, 200, 340);

        MainScreen.add(Sidebar);
        Sidebar.setBounds(0, 0, 200, 600);

        MainCardPane.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setLayout(null);

        Home_Text1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Home_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home_Text1.setText("Hello");
        Home.add(Home_Text1);
        Home_Text1.setBounds(0, 40, 1000, 48);

        Home_Text2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Home_Text2.setForeground(new java.awt.Color(102, 102, 102));
        Home_Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home_Text2.setText("Please Choose Your 1 Month Diet Plan");
        Home.add(Home_Text2);
        Home_Text2.setBounds(280, 90, 440, 32);

        Home_Info1.setBackground(new java.awt.Color(255, 255, 255));
        Home_Info1.setLayout(null);

        Home_Icon1.setBackground(new java.awt.Color(254, 232, 204));
        Home_Icon1.setLayout(null);

        Home_Icon1_Text1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Home_Icon1_Text1.setForeground(new java.awt.Color(102, 102, 102));
        Home_Icon1_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home_Icon1_Text1.setText("Bulking");
        Home_Icon1.add(Home_Icon1_Text1);
        Home_Icon1_Text1.setBounds(0, 100, 170, 40);

        Home_Icon1_Text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home_Icon1_Text2.setForeground(new java.awt.Color(102, 102, 102));
        Home_Icon1_Text2.setText("calorie > energy");
        Home_Icon1.add(Home_Icon1_Text2);
        Home_Icon1_Text2.setBounds(30, 130, 111, 20);

        Home_Info1.add(Home_Icon1);
        Home_Icon1.setBounds(0, 0, 170, 170);

        Home_Info1_Text1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home_Info1_Text1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Info1_Text1.setText("Bulking is the muscle-gaining phase. You're meant to");
        Home_Info1.add(Home_Info1_Text1);
        Home_Info1_Text1.setBounds(190, 40, 450, 25);

        Home_Info1_Text2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home_Info1_Text2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Info1_Text2.setText("intentionally consume more calories than your body ");
        Home_Info1.add(Home_Info1_Text2);
        Home_Info1_Text2.setBounds(190, 70, 450, 25);

        Home_Info1_Text3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home_Info1_Text3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Info1_Text3.setText("needs for a 1 month period");
        Home_Info1.add(Home_Info1_Text3);
        Home_Info1_Text3.setBounds(190, 100, 450, 25);

        Home.add(Home_Info1);
        Home_Info1.setBounds(170, 160, 660, 170);

        Home_Info2.setBackground(new java.awt.Color(255, 255, 255));
        Home_Info2.setLayout(null);

        Home_Icon2.setBackground(new java.awt.Color(204, 255, 255));
        Home_Icon2.setLayout(null);

        Home_Icon2_Text1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Home_Icon2_Text1.setForeground(new java.awt.Color(102, 102, 102));
        Home_Icon2_Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home_Icon2_Text1.setText("Cutting");
        Home_Icon2.add(Home_Icon2_Text1);
        Home_Icon2_Text1.setBounds(0, 100, 170, 40);

        Home_Icon2_Text2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Home_Icon2_Text2.setForeground(new java.awt.Color(102, 102, 102));
        Home_Icon2_Text2.setText("calorie < energy");
        Home_Icon2.add(Home_Icon2_Text2);
        Home_Icon2_Text2.setBounds(30, 130, 111, 20);

        Home_Info2.add(Home_Icon2);
        Home_Icon2.setBounds(0, 0, 170, 170);

        Home_Info2_Text1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home_Info2_Text1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Info2_Text1.setText("muscle mass as possible");
        Home_Info2.add(Home_Info2_Text1);
        Home_Info2_Text1.setBounds(190, 100, 450, 25);

        Home_Info2_Text2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home_Info2_Text2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Info2_Text2.setText("Cutting is a period of eating at a calorie deficit as a");
        Home_Info2.add(Home_Info2_Text2);
        Home_Info2_Text2.setBounds(190, 40, 450, 25);

        Home_Info2_Text3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Home_Info2_Text3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home_Info2_Text3.setText("means to lose body fat while maintaining as much");
        Home_Info2.add(Home_Info2_Text3);
        Home_Info2_Text3.setBounds(190, 70, 450, 25);

        Home.add(Home_Info2);
        Home_Info2.setBounds(170, 380, 660, 170);

        MainCardPane.add(Home, "card2");

        Plan.setBackground(new java.awt.Color(255, 255, 255));
        Plan.setLayout(null);

        Plan_HeaderBackground.setBackground(new java.awt.Color(94, 173, 81));
        Plan_HeaderBackground.setLayout(null);

        Plan_BtnDay1.setBackground(new java.awt.Color(94, 173, 81));
        Plan_BtnDay1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plan_BtnDay1.setForeground(new java.awt.Color(255, 255, 255));
        Plan_BtnDay1.setText("Day 1");
        Plan_BtnDay1.setBorder(null);
        Plan_BtnDay1.setBorderPainted(false);
        Plan_BtnDay1.setFocusable(false);
        Plan_BtnDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_BtnDay1ActionPerformed(evt);
            }
        });
        Plan_HeaderBackground.add(Plan_BtnDay1);
        Plan_BtnDay1.setBounds(240, 30, 70, 30);

        Plan_BtnDay2.setBackground(new java.awt.Color(94, 173, 81));
        Plan_BtnDay2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plan_BtnDay2.setForeground(new java.awt.Color(255, 255, 255));
        Plan_BtnDay2.setText("Day 2");
        Plan_BtnDay2.setBorder(null);
        Plan_BtnDay2.setBorderPainted(false);
        Plan_BtnDay2.setFocusable(false);
        Plan_BtnDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_BtnDay2ActionPerformed(evt);
            }
        });
        Plan_HeaderBackground.add(Plan_BtnDay2);
        Plan_BtnDay2.setBounds(330, 30, 70, 30);

        Plan_BtnDay3.setBackground(new java.awt.Color(94, 173, 81));
        Plan_BtnDay3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plan_BtnDay3.setForeground(new java.awt.Color(255, 255, 255));
        Plan_BtnDay3.setText("Day 3");
        Plan_BtnDay3.setBorder(null);
        Plan_BtnDay3.setBorderPainted(false);
        Plan_BtnDay3.setFocusable(false);
        Plan_BtnDay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_BtnDay3ActionPerformed(evt);
            }
        });
        Plan_HeaderBackground.add(Plan_BtnDay3);
        Plan_BtnDay3.setBounds(420, 30, 70, 30);

        Plan_BtnDay4.setBackground(new java.awt.Color(94, 173, 81));
        Plan_BtnDay4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plan_BtnDay4.setForeground(new java.awt.Color(255, 255, 255));
        Plan_BtnDay4.setText("Day 4");
        Plan_BtnDay4.setBorder(null);
        Plan_BtnDay4.setBorderPainted(false);
        Plan_BtnDay4.setFocusable(false);
        Plan_BtnDay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_BtnDay4ActionPerformed(evt);
            }
        });
        Plan_HeaderBackground.add(Plan_BtnDay4);
        Plan_BtnDay4.setBounds(510, 30, 70, 30);

        Plan_BtnDay5.setBackground(new java.awt.Color(94, 173, 81));
        Plan_BtnDay5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plan_BtnDay5.setForeground(new java.awt.Color(255, 255, 255));
        Plan_BtnDay5.setText("Day 5");
        Plan_BtnDay5.setBorder(null);
        Plan_BtnDay5.setBorderPainted(false);
        Plan_BtnDay5.setFocusable(false);
        Plan_BtnDay5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_BtnDay5ActionPerformed(evt);
            }
        });
        Plan_HeaderBackground.add(Plan_BtnDay5);
        Plan_BtnDay5.setBounds(600, 30, 70, 30);

        Plan_BtnDay6.setBackground(new java.awt.Color(94, 173, 81));
        Plan_BtnDay6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Plan_BtnDay6.setForeground(new java.awt.Color(255, 255, 255));
        Plan_BtnDay6.setText("Day 6");
        Plan_BtnDay6.setBorder(null);
        Plan_BtnDay6.setBorderPainted(false);
        Plan_BtnDay6.setFocusable(false);
        Plan_BtnDay6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plan_BtnDay6ActionPerformed(evt);
            }
        });
        Plan_HeaderBackground.add(Plan_BtnDay6);
        Plan_BtnDay6.setBounds(690, 30, 70, 30);

        Plan.add(Plan_HeaderBackground);
        Plan_HeaderBackground.setBounds(0, 0, 1000, 90);

        Plan_CardPane.setBackground(new java.awt.Color(255, 255, 255));
        Plan_CardPane.setToolTipText("");
        Plan_CardPane.setLayout(new java.awt.CardLayout());

        Plan_GridPane.setBackground(new java.awt.Color(255, 255, 255));
        Plan_GridPane.setLayout(new java.awt.GridLayout(1, 3));

        Breakfast.setBackground(new java.awt.Color(255, 255, 255));
        Breakfast.setLayout(null);

        Breakfast_Header.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Breakfast_Header.setForeground(new java.awt.Color(145, 199, 136));
        Breakfast_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Breakfast_Header.setText("Breakfast");
        Breakfast.add(Breakfast_Header);
        Breakfast_Header.setBounds(0, 20, 330, 25);

        Breakfast_Carbo.setBackground(new java.awt.Color(254, 232, 204));
        Breakfast_Carbo.setLayout(null);

        Breakfast_Carbo_Line.setBackground(new java.awt.Color(254, 232, 204));
        Breakfast_Carbo_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(250, 165, 55)));

        Brreakfast_Carbo_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Brreakfast_Carbo_Header.setText("Carbo");

        javax.swing.GroupLayout Breakfast_Carbo_LineLayout = new javax.swing.GroupLayout(Breakfast_Carbo_Line);
        Breakfast_Carbo_Line.setLayout(Breakfast_Carbo_LineLayout);
        Breakfast_Carbo_LineLayout.setHorizontalGroup(
            Breakfast_Carbo_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Breakfast_Carbo_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brreakfast_Carbo_Header)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Breakfast_Carbo_LineLayout.setVerticalGroup(
            Breakfast_Carbo_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Breakfast_Carbo_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brreakfast_Carbo_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Breakfast_Carbo.add(Breakfast_Carbo_Line);
        Breakfast_Carbo_Line.setBounds(10, 0, 110, 30);

        Breakfast_Carbo_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Breakfast_Carbo.add(Breakfast_Carbo_FoodName);
        Breakfast_Carbo_FoodName.setBounds(10, 40, 230, 50);

        Breakfast.add(Breakfast_Carbo);
        Breakfast_Carbo.setBounds(40, 70, 250, 100);

        Breakfast_Vegie.setBackground(new java.awt.Color(222, 238, 220));
        Breakfast_Vegie.setLayout(null);

        Breakfast_Vegie_Line.setBackground(new java.awt.Color(222, 238, 220));
        Breakfast_Vegie_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(125, 188, 117)));
        Breakfast_Vegie_Line.setToolTipText("");

        Brreakfast_Vegie_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Brreakfast_Vegie_Header.setText("Vegie");

        javax.swing.GroupLayout Breakfast_Vegie_LineLayout = new javax.swing.GroupLayout(Breakfast_Vegie_Line);
        Breakfast_Vegie_Line.setLayout(Breakfast_Vegie_LineLayout);
        Breakfast_Vegie_LineLayout.setHorizontalGroup(
            Breakfast_Vegie_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Breakfast_Vegie_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brreakfast_Vegie_Header)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Breakfast_Vegie_LineLayout.setVerticalGroup(
            Breakfast_Vegie_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Breakfast_Vegie_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brreakfast_Vegie_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Breakfast_Vegie.add(Breakfast_Vegie_Line);
        Breakfast_Vegie_Line.setBounds(10, 0, 110, 30);

        Breakfast_Vegie_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Breakfast_Vegie.add(Breakfast_Vegie_FoodName);
        Breakfast_Vegie_FoodName.setBounds(10, 40, 230, 50);

        Breakfast.add(Breakfast_Vegie);
        Breakfast_Vegie.setBounds(40, 220, 250, 100);

        Breakfast_Protein.setBackground(new java.awt.Color(255, 204, 255));
        Breakfast_Protein.setLayout(null);

        Breakfast_Protein_Line.setBackground(new java.awt.Color(255, 204, 255));
        Breakfast_Protein_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 51, 254)));

        Brreakfast_Protein_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Brreakfast_Protein_Header.setText("Protein");

        javax.swing.GroupLayout Breakfast_Protein_LineLayout = new javax.swing.GroupLayout(Breakfast_Protein_Line);
        Breakfast_Protein_Line.setLayout(Breakfast_Protein_LineLayout);
        Breakfast_Protein_LineLayout.setHorizontalGroup(
            Breakfast_Protein_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Breakfast_Protein_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brreakfast_Protein_Header)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Breakfast_Protein_LineLayout.setVerticalGroup(
            Breakfast_Protein_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Breakfast_Protein_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brreakfast_Protein_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Breakfast_Protein.add(Breakfast_Protein_Line);
        Breakfast_Protein_Line.setBounds(10, 0, 110, 30);

        Breakfast_Protein_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Breakfast_Protein.add(Breakfast_Protein_FoodName);
        Breakfast_Protein_FoodName.setBounds(10, 40, 230, 50);

        Breakfast.add(Breakfast_Protein);
        Breakfast_Protein.setBounds(40, 370, 250, 100);

        Plan_GridPane.add(Breakfast);

        Lunch.setBackground(new java.awt.Color(255, 255, 255));
        Lunch.setLayout(null);

        Lunch_Header.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lunch_Header.setForeground(new java.awt.Color(145, 199, 136));
        Lunch_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lunch_Header.setText("Lunch");
        Lunch.add(Lunch_Header);
        Lunch_Header.setBounds(0, 20, 330, 25);

        Lunch_Carbo.setBackground(new java.awt.Color(254, 232, 204));
        Lunch_Carbo.setLayout(null);

        Lunch_Carbo_Line.setBackground(new java.awt.Color(254, 232, 204));
        Lunch_Carbo_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(250, 165, 55)));

        Lunch_Carbo_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lunch_Carbo_Header.setText("Carbo");

        javax.swing.GroupLayout Lunch_Carbo_LineLayout = new javax.swing.GroupLayout(Lunch_Carbo_Line);
        Lunch_Carbo_Line.setLayout(Lunch_Carbo_LineLayout);
        Lunch_Carbo_LineLayout.setHorizontalGroup(
            Lunch_Carbo_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lunch_Carbo_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lunch_Carbo_Header)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Lunch_Carbo_LineLayout.setVerticalGroup(
            Lunch_Carbo_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lunch_Carbo_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lunch_Carbo_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Lunch_Carbo.add(Lunch_Carbo_Line);
        Lunch_Carbo_Line.setBounds(10, 0, 110, 30);

        Lunch_Carbo_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lunch_Carbo.add(Lunch_Carbo_FoodName);
        Lunch_Carbo_FoodName.setBounds(10, 40, 230, 50);

        Lunch.add(Lunch_Carbo);
        Lunch_Carbo.setBounds(40, 70, 250, 100);

        Lunch_Vegie.setBackground(new java.awt.Color(222, 238, 220));
        Lunch_Vegie.setLayout(null);

        Lunch_Vegie_Line.setBackground(new java.awt.Color(222, 238, 220));
        Lunch_Vegie_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(125, 188, 117)));
        Lunch_Vegie_Line.setToolTipText("");

        Lunch_Vegie_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lunch_Vegie_Header.setText("Vegie");

        javax.swing.GroupLayout Lunch_Vegie_LineLayout = new javax.swing.GroupLayout(Lunch_Vegie_Line);
        Lunch_Vegie_Line.setLayout(Lunch_Vegie_LineLayout);
        Lunch_Vegie_LineLayout.setHorizontalGroup(
            Lunch_Vegie_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lunch_Vegie_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lunch_Vegie_Header)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Lunch_Vegie_LineLayout.setVerticalGroup(
            Lunch_Vegie_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lunch_Vegie_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lunch_Vegie_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Lunch_Vegie.add(Lunch_Vegie_Line);
        Lunch_Vegie_Line.setBounds(10, 0, 110, 30);

        Lunch_Vegie_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lunch_Vegie.add(Lunch_Vegie_FoodName);
        Lunch_Vegie_FoodName.setBounds(10, 40, 230, 50);

        Lunch.add(Lunch_Vegie);
        Lunch_Vegie.setBounds(40, 220, 250, 100);

        Breakfast_Protein1.setBackground(new java.awt.Color(255, 204, 255));
        Breakfast_Protein1.setLayout(null);

        Lunch_Protein_Line.setBackground(new java.awt.Color(255, 204, 255));
        Lunch_Protein_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 51, 254)));

        Lunch_Protein_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lunch_Protein_Header.setText("Protein");

        javax.swing.GroupLayout Lunch_Protein_LineLayout = new javax.swing.GroupLayout(Lunch_Protein_Line);
        Lunch_Protein_Line.setLayout(Lunch_Protein_LineLayout);
        Lunch_Protein_LineLayout.setHorizontalGroup(
            Lunch_Protein_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lunch_Protein_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lunch_Protein_Header)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Lunch_Protein_LineLayout.setVerticalGroup(
            Lunch_Protein_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lunch_Protein_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lunch_Protein_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Breakfast_Protein1.add(Lunch_Protein_Line);
        Lunch_Protein_Line.setBounds(10, 0, 110, 30);

        Lunch_Protein_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Breakfast_Protein1.add(Lunch_Protein_FoodName);
        Lunch_Protein_FoodName.setBounds(10, 40, 230, 50);

        Lunch.add(Breakfast_Protein1);
        Breakfast_Protein1.setBounds(40, 370, 250, 100);

        Plan_GridPane.add(Lunch);

        Dinner.setBackground(new java.awt.Color(255, 255, 255));
        Dinner.setLayout(null);

        Breakfast_Header2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Breakfast_Header2.setForeground(new java.awt.Color(145, 199, 136));
        Breakfast_Header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Breakfast_Header2.setText("Dinner");
        Dinner.add(Breakfast_Header2);
        Breakfast_Header2.setBounds(0, 20, 330, 25);

        Dinner_Carbo.setBackground(new java.awt.Color(254, 232, 204));
        Dinner_Carbo.setLayout(null);

        Dinner_Carbo_Line.setBackground(new java.awt.Color(254, 232, 204));
        Dinner_Carbo_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(250, 165, 55)));

        Dinner_Carbo_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dinner_Carbo_Header.setText("Carbo");

        javax.swing.GroupLayout Dinner_Carbo_LineLayout = new javax.swing.GroupLayout(Dinner_Carbo_Line);
        Dinner_Carbo_Line.setLayout(Dinner_Carbo_LineLayout);
        Dinner_Carbo_LineLayout.setHorizontalGroup(
            Dinner_Carbo_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dinner_Carbo_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dinner_Carbo_Header)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Dinner_Carbo_LineLayout.setVerticalGroup(
            Dinner_Carbo_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dinner_Carbo_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dinner_Carbo_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dinner_Carbo.add(Dinner_Carbo_Line);
        Dinner_Carbo_Line.setBounds(10, 0, 110, 30);

        Dinner_Carbo_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dinner_Carbo.add(Dinner_Carbo_FoodName);
        Dinner_Carbo_FoodName.setBounds(10, 40, 230, 50);

        Dinner.add(Dinner_Carbo);
        Dinner_Carbo.setBounds(40, 70, 250, 100);

        Dinner_Vegie.setBackground(new java.awt.Color(222, 238, 220));
        Dinner_Vegie.setLayout(null);

        Dinner_Vegie_Line.setBackground(new java.awt.Color(222, 238, 220));
        Dinner_Vegie_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(125, 188, 117)));
        Dinner_Vegie_Line.setToolTipText("");

        Dinner_Vegie_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dinner_Vegie_Header.setText("Vegie");

        javax.swing.GroupLayout Dinner_Vegie_LineLayout = new javax.swing.GroupLayout(Dinner_Vegie_Line);
        Dinner_Vegie_Line.setLayout(Dinner_Vegie_LineLayout);
        Dinner_Vegie_LineLayout.setHorizontalGroup(
            Dinner_Vegie_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dinner_Vegie_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dinner_Vegie_Header)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        Dinner_Vegie_LineLayout.setVerticalGroup(
            Dinner_Vegie_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dinner_Vegie_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dinner_Vegie_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dinner_Vegie.add(Dinner_Vegie_Line);
        Dinner_Vegie_Line.setBounds(10, 0, 110, 30);

        Dinner_Vegie_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dinner_Vegie.add(Dinner_Vegie_FoodName);
        Dinner_Vegie_FoodName.setBounds(10, 40, 230, 50);

        Dinner.add(Dinner_Vegie);
        Dinner_Vegie.setBounds(40, 220, 250, 100);

        Dinner_Protein.setBackground(new java.awt.Color(255, 204, 255));
        Dinner_Protein.setLayout(null);

        Dinner_Protein_Line.setBackground(new java.awt.Color(255, 204, 255));
        Dinner_Protein_Line.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 51, 254)));

        Dinner_Protein_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dinner_Protein_Header.setText("Protein");

        javax.swing.GroupLayout Dinner_Protein_LineLayout = new javax.swing.GroupLayout(Dinner_Protein_Line);
        Dinner_Protein_Line.setLayout(Dinner_Protein_LineLayout);
        Dinner_Protein_LineLayout.setHorizontalGroup(
            Dinner_Protein_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dinner_Protein_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dinner_Protein_Header)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        Dinner_Protein_LineLayout.setVerticalGroup(
            Dinner_Protein_LineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dinner_Protein_LineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dinner_Protein_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dinner_Protein.add(Dinner_Protein_Line);
        Dinner_Protein_Line.setBounds(10, 0, 110, 30);

        Dinner_Protein_FoodName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dinner_Protein.add(Dinner_Protein_FoodName);
        Dinner_Protein_FoodName.setBounds(10, 40, 230, 50);

        Dinner.add(Dinner_Protein);
        Dinner_Protein.setBounds(40, 370, 250, 100);

        Plan_GridPane.add(Dinner);

        Plan_CardPane.add(Plan_GridPane, "card2");

        Plan.add(Plan_CardPane);
        Plan_CardPane.setBounds(0, 90, 1000, 510);

        MainCardPane.add(Plan, "card3");

        Stat.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PROGRESS");
        Stat.add(jLabel3);
        jLabel3.setBounds(0, 280, 1010, 64);

        MainCardPane.add(Stat, "card4");

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.setLayout(null);

        Profile_Header.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Profile_Header.setForeground(new java.awt.Color(153, 214, 118));
        Profile_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile_Header.setText("Profile");
        Profile.add(Profile_Header);
        Profile_Header.setBounds(0, 0, 210, 70);

        Profile_UserPicture.setIcon(new javax.swing.ImageIcon("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\gambar\\messageImage_1673886200554.jpg")); // NOI18N
        Profile.add(Profile_UserPicture);
        Profile_UserPicture.setBounds(110, 150, 300, 300);

        ScrollPane1.setBorder(null);

        Profile_UserName.setBorder(null);
        Profile_UserName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Profile_UserName.setText("Gian Guido");
        ScrollPane1.setViewportView(Profile_UserName);

        Profile.add(ScrollPane1);
        ScrollPane1.setBounds(210, 460, 110, 25);

        Profile_Icon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\gambar\\profile.png")); // NOI18N
        Profile_Icon1.setText("jLabel6");
        Profile.add(Profile_Icon1);
        Profile_Icon1.setBounds(520, 130, 150, 150);

        Profile_Icon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\gambar\\REnew.png")); // NOI18N
        Profile_Icon2.setText("jLabel7");
        Profile.add(Profile_Icon2);
        Profile_Icon2.setBounds(520, 290, 140, 150);

        Profile_Icon3.setIcon(new javax.swing.ImageIcon("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\gambar\\sett.png")); // NOI18N
        Profile_Icon3.setText("jLabel8");
        Profile.add(Profile_Icon3);
        Profile_Icon3.setBounds(700, 130, 150, 150);

        Profile_Icon4.setIcon(new javax.swing.ImageIcon("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\gambar\\Screenshot 2023-01-16 234344.png")); // NOI18N
        Profile_Icon4.setText("jLabel9");
        Profile.add(Profile_Icon4);
        Profile_Icon4.setBounds(710, 280, 160, 170);

        MainCardPane.add(Profile, "card5");

        Nutrionist.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PROGRESS");
        Nutrionist.add(jLabel4);
        jLabel4.setBounds(0, 280, 1010, 64);

        MainCardPane.add(Nutrionist, "card4");

        MainScreen.add(MainCardPane);
        MainCardPane.setBounds(200, 0, 1000, 600);

        background.add(MainScreen);
        MainScreen.setBounds(0, 0, 1200, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
        Home.setVisible(true);
        Home_Status.setBackground(new Color(255, 255, 0));
        Plan.setVisible(false);
        Plan_Status.setBackground(new Color(204, 204, 204));
        Stat.setVisible(false);
        Stat_Status.setBackground(new Color(204, 204, 204));
        Profile.setVisible(false);
        Profile_Status.setBackground(new Color(204, 204, 204));
        Nutrionist.setVisible(false);
        Add_Status.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlanActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Home_Status.setBackground(new Color(204, 204, 204));
        Plan.setVisible(true);
        Plan_Status.setBackground(new Color(255, 255, 0));
        Stat.setVisible(false);
        Stat_Status.setBackground(new Color(204, 204, 204));
        Profile.setVisible(false);
        Profile_Status.setBackground(new Color(204, 204, 204));
        Nutrionist.setVisible(false);
        Add_Status.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_BtnPlanActionPerformed

    private void BtnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStatActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Home_Status.setBackground(new Color(204, 204, 204));
        Plan.setVisible(false);
        Plan_Status.setBackground(new Color(204, 204, 204));
        Stat.setVisible(true);
        Stat_Status.setBackground(new Color(255, 255, 0));
        Profile.setVisible(false);
        Profile_Status.setBackground(new Color(204, 204, 204));
        Nutrionist.setVisible(false);
        Add_Status.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_BtnStatActionPerformed

    private void BtnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfileActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Home_Status.setBackground(new Color(204, 204, 204));
        Plan.setVisible(false);
        Plan_Status.setBackground(new Color(204, 204, 204));
        Stat.setVisible(false);
        Stat_Status.setBackground(new Color(204, 204, 204));
        Profile.setVisible(true);
        Profile_Status.setBackground(new Color(255, 255, 0));
        Nutrionist.setVisible(false);
        Add_Status.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_BtnProfileActionPerformed

    private void Plan_BtnDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_BtnDay1ActionPerformed
        // TODO add your handling code here:
        File file = new File ("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\GetFit Pro\\GetFit\\src\\main\\java\\com\\mycompany\\getfit\\cutting_plan.txt");
        Scanner scan;
        try {
            scan = new Scanner (file);
            scan.nextLine();
            Breakfast_Carbo_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Breakfast_Vegie_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Breakfast_Protein_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Lunch_Carbo_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Lunch_Vegie_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Lunch_Protein_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Dinner_Carbo_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Dinner_Vegie_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Dinner_Protein_FoodName.setText(scan.nextLine());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Plan_BtnDay1ActionPerformed

    private void Plan_BtnDay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_BtnDay2ActionPerformed
        // TODO add your handling code here:
        File file = new File ("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\GetFit Pro\\GetFit\\src\\main\\java\\com\\mycompany\\getfit\\cutting_plan.txt");
        Scanner scan;
        try {
            scan = new Scanner (file);
            for(int x=0; x<30; x++){
                scan.nextLine();
            }
            Breakfast_Carbo_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Breakfast_Vegie_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Breakfast_Protein_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Lunch_Carbo_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Lunch_Vegie_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Lunch_Protein_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Dinner_Carbo_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Dinner_Vegie_FoodName.setText(scan.nextLine());
            scan.nextLine();
            scan.nextLine();
            Dinner_Protein_FoodName.setText(scan.nextLine());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Plan_BtnDay2ActionPerformed

    private void Plan_BtnDay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_BtnDay3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plan_BtnDay3ActionPerformed

    private void Plan_BtnDay4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_BtnDay4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plan_BtnDay4ActionPerformed

    private void Plan_BtnDay5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_BtnDay5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plan_BtnDay5ActionPerformed

    private void Plan_BtnDay6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plan_BtnDay6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Plan_BtnDay6ActionPerformed

    private void Login_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_emailFocusGained
        // TODO add your handling code here:
        String text = Login_email.getText();
        if(text.equals("e-mail")){
            Login_email.setText("");
        }
    }//GEN-LAST:event_Login_emailFocusGained

    private void Login_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_emailFocusLost
        // TODO add your handling code here:
        String text = Login_email.getText();
        if(text.equals("")){
            Login_email.setText("e-mail");
        }
    }//GEN-LAST:event_Login_emailFocusLost

    private void Login_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_passwordFocusGained
        // TODO add your handling code here:
        String text = Login_password.getText();
        if(text.equals("password")){
            Login_password.setText("");
        }
    }//GEN-LAST:event_Login_passwordFocusGained

    private void Login_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Login_passwordFocusLost
        // TODO add your handling code here:
        String text = Login_password.getText();
        if(text.equals("")){
            Login_password.setText("password");
        }
    }//GEN-LAST:event_Login_passwordFocusLost

    private void Login_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_radioActionPerformed

    private void Login_BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BtnSubmitActionPerformed
        // TODO add your handling code here:
        // Login
        File file = new File("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\GetFit Pro\\GetFit\\src\\main\\java\\com\\mycompany\\getfit\\client.txt");
        ArrayList<String> email = new ArrayList<String>();
        ArrayList<String> password = new ArrayList<String>();
        ArrayList<String> status = new ArrayList<String>();
        String inputed_email = Login_email.getText();
        String inputed_password = Login_password.getText();
        
        try {
            // Read File
            Scanner scan = new Scanner(file);
            while(scan.hasNextLine()){
                email.add(scan.next());
                password.add(scan.next());
                status.add(scan.nextLine());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Checking
        for(int x=0; x<=email.size(); x++){
            if(inputed_email.equals(email.get(x))){
                if(inputed_password.equals(password.get(x))){
                    Login_Background.setVisible(false);
                    MainScreen.setVisible(true);
                    Sidebar_Nutrionist.setVisible(false);
                    System.out.println(status.get(x));
                    if(status.get(x).equals("admin")){
                        // Show Admin Bar
                        
                    }else if(status.get(x).equals("nutrionist")){
                        // Show Nutrionist Bar
                        Sidebar_Nutrionist.setVisible(true);
                    }
                    
                    break;
                }
            }
        }
        
        // <not finished>
        // Cutting List
//        File file2 = new File("C:\\Users\\eric_\\Desktop\\Documents\\1Materi CS\\Semester 3\\OOP\\1Project\\GetFit Pro\\GetFit\\src\\main\\java\\com\\mycompany\\getfit\\cutting_plan.txt");
//        try{
//            Scanner scan = new Scanner(file2);
//            while(scan.hasNextLine()){
//                String day = scan.nextLine();
//                BreakfastList.add(new Breakfast(day, "Carbo", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                BreakfastList.add(new Breakfast(day, "Vegie", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                BreakfastList.add(new Breakfast(day, "Protein", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                LunchList.add(new Lunch(day, "Carbo", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                LunchList.add(new Lunch(day, "Vegie", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                LunchList.add(new Lunch(day, "Protein", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                DinnerList.add(new Dinner(day, "Carbo", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                DinnerList.add(new Dinner(day, "Vegie", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                DinnerList.add(new Dinner(day, "Protein", scan.nextLine(), scan.nextLine(), scan.nextLine()));
//                scan.nextLine();
//            }
//        } catch (Exception e){}
//        System.out.println(BreakfastList.get(3).getName());
    }//GEN-LAST:event_Login_BtnSubmitActionPerformed

    private void Onboard_BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Onboard_BtnNextActionPerformed
        // TODO add your handling code here:
        Onboarding.setVisible(false);
        Login_Background.setVisible(true);
    }//GEN-LAST:event_Onboard_BtnNextActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        Home.setVisible(false);
        Home_Status.setBackground(new Color(204, 204, 204));
        Plan.setVisible(false);
        Plan_Status.setBackground(new Color(204, 204, 204));
        Stat.setVisible(false);
        Stat_Status.setBackground(new Color(204, 204, 204));
        Profile.setVisible(false);
        Profile_Status.setBackground(new Color(204, 204, 204));
        Nutrionist.setVisible(true);
        Add_Status.setBackground(new Color(255, 255, 0));
    }//GEN-LAST:event_BtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    
    static ArrayList<Breakfast> BreakfastList = new ArrayList<>();
    static ArrayList<Lunch> LunchList = new ArrayList<>();
    static ArrayList<Dinner> DinnerList = new ArrayList<>();
    static ArrayList<Client> ClientList = new ArrayList<>();
    static ArrayList<Nutrionist> NutrionistList = new ArrayList<>();
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Icon;
    private javax.swing.JPanel Add_Status;
    private javax.swing.JPanel Breakfast;
    private javax.swing.JPanel Breakfast_Carbo;
    private javax.swing.JLabel Breakfast_Carbo_FoodName;
    private javax.swing.JPanel Breakfast_Carbo_Line;
    private javax.swing.JLabel Breakfast_Header;
    private javax.swing.JLabel Breakfast_Header2;
    private javax.swing.JPanel Breakfast_Protein;
    private javax.swing.JPanel Breakfast_Protein1;
    private javax.swing.JLabel Breakfast_Protein_FoodName;
    private javax.swing.JPanel Breakfast_Protein_Line;
    private javax.swing.JPanel Breakfast_Vegie;
    private javax.swing.JLabel Breakfast_Vegie_FoodName;
    private javax.swing.JPanel Breakfast_Vegie_Line;
    private javax.swing.JLabel Brreakfast_Carbo_Header;
    private javax.swing.JLabel Brreakfast_Protein_Header;
    private javax.swing.JLabel Brreakfast_Vegie_Header;
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnPlan;
    private javax.swing.JButton BtnProfile;
    private javax.swing.JButton BtnStat;
    private javax.swing.JPanel Dinner;
    private javax.swing.JPanel Dinner_Carbo;
    private javax.swing.JLabel Dinner_Carbo_FoodName;
    private javax.swing.JLabel Dinner_Carbo_Header;
    private javax.swing.JPanel Dinner_Carbo_Line;
    private javax.swing.JPanel Dinner_Protein;
    private javax.swing.JLabel Dinner_Protein_FoodName;
    private javax.swing.JLabel Dinner_Protein_Header;
    private javax.swing.JPanel Dinner_Protein_Line;
    private javax.swing.JPanel Dinner_Vegie;
    private javax.swing.JLabel Dinner_Vegie_FoodName;
    private javax.swing.JLabel Dinner_Vegie_Header;
    private javax.swing.JPanel Dinner_Vegie_Line;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home_Icon;
    private javax.swing.JPanel Home_Icon1;
    private javax.swing.JLabel Home_Icon1_Text1;
    private javax.swing.JLabel Home_Icon1_Text2;
    private javax.swing.JPanel Home_Icon2;
    private javax.swing.JLabel Home_Icon2_Text1;
    private javax.swing.JLabel Home_Icon2_Text2;
    private javax.swing.JPanel Home_Info1;
    private javax.swing.JLabel Home_Info1_Text1;
    private javax.swing.JLabel Home_Info1_Text2;
    private javax.swing.JLabel Home_Info1_Text3;
    private javax.swing.JPanel Home_Info2;
    private javax.swing.JLabel Home_Info2_Text1;
    private javax.swing.JLabel Home_Info2_Text2;
    private javax.swing.JLabel Home_Info2_Text3;
    public javax.swing.JPanel Home_Status;
    private javax.swing.JLabel Home_Text1;
    private javax.swing.JLabel Home_Text2;
    private javax.swing.JPanel Login;
    public javax.swing.JPanel Login_Background;
    private javax.swing.JButton Login_BtnSubmit;
    private javax.swing.JPanel Login_Facebook;
    private javax.swing.JPanel Login_Gmail;
    private javax.swing.JLabel Login_Header;
    private javax.swing.JPanel Login_Line1;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JLabel Login_Text1;
    private javax.swing.JLabel Login_Text2;
    private javax.swing.JPanel Login_Twitter;
    private javax.swing.JTextPane Login_email;
    private javax.swing.JPanel Login_extra;
    private javax.swing.JPasswordField Login_password;
    private javax.swing.JRadioButton Login_radio;
    private javax.swing.JLabel Login_text1;
    private javax.swing.JLabel Login_text2;
    private javax.swing.JPanel Lunch;
    private javax.swing.JPanel Lunch_Carbo;
    private javax.swing.JLabel Lunch_Carbo_FoodName;
    private javax.swing.JLabel Lunch_Carbo_Header;
    private javax.swing.JPanel Lunch_Carbo_Line;
    private javax.swing.JLabel Lunch_Header;
    private javax.swing.JLabel Lunch_Protein_FoodName;
    private javax.swing.JLabel Lunch_Protein_Header;
    private javax.swing.JPanel Lunch_Protein_Line;
    private javax.swing.JPanel Lunch_Vegie;
    private javax.swing.JLabel Lunch_Vegie_FoodName;
    private javax.swing.JLabel Lunch_Vegie_Header;
    private javax.swing.JPanel Lunch_Vegie_Line;
    private javax.swing.JPanel MainCardPane;
    public javax.swing.JPanel MainScreen;
    private javax.swing.JPanel Nutrionist;
    public javax.swing.JButton Onboard_BtnNext;
    private javax.swing.JPanel Onboard_Info;
    public javax.swing.JPanel Onboard_Info1;
    private javax.swing.JLabel Onboard_Info1_Header;
    private javax.swing.JPanel Onboard_Info1_Picture;
    private javax.swing.JLabel Onboard_Info1_Text1;
    private javax.swing.JLabel Onboard_Info1_Text2;
    public javax.swing.JPanel Onboard_Info2;
    private javax.swing.JLabel Onboard_Info2_Header;
    private javax.swing.JPanel Onboard_Info2_Picture;
    private javax.swing.JLabel Onboard_Info2_Text1;
    private javax.swing.JLabel Onboard_Info2_Text2;
    public javax.swing.JPanel Onboard_Info3;
    private javax.swing.JLabel Onboard_Info3_Header;
    private javax.swing.JPanel Onboard_Info3_Picture;
    private javax.swing.JLabel Onboard_Info3_Text1;
    private javax.swing.JLabel Onboard_Info3_Text2;
    public javax.swing.JPanel Onboarding;
    private javax.swing.JPanel Plan;
    private javax.swing.JButton Plan_BtnDay1;
    private javax.swing.JButton Plan_BtnDay2;
    private javax.swing.JButton Plan_BtnDay3;
    private javax.swing.JButton Plan_BtnDay4;
    private javax.swing.JButton Plan_BtnDay5;
    private javax.swing.JButton Plan_BtnDay6;
    private javax.swing.JPanel Plan_CardPane;
    private javax.swing.JPanel Plan_GridPane;
    private javax.swing.JPanel Plan_HeaderBackground;
    private javax.swing.JPanel Plan_Icon;
    private javax.swing.JPanel Plan_Status;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel Profile_Header;
    private javax.swing.JPanel Profile_Icon;
    private javax.swing.JLabel Profile_Icon1;
    private javax.swing.JLabel Profile_Icon2;
    private javax.swing.JLabel Profile_Icon3;
    private javax.swing.JLabel Profile_Icon4;
    private javax.swing.JPanel Profile_Status;
    private javax.swing.JTextPane Profile_UserName;
    private javax.swing.JLabel Profile_UserPicture;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel Sidebar_Header;
    private javax.swing.JPanel Sidebar_Home;
    private javax.swing.JPanel Sidebar_List;
    private javax.swing.JPanel Sidebar_Nutrionist;
    private javax.swing.JPanel Sidebar_Plan;
    private javax.swing.JPanel Sidebar_Profile;
    private javax.swing.JPanel Sidebar_Stat;
    public javax.swing.JPanel Splash;
    public javax.swing.JProgressBar Splash_ProgressBar;
    private javax.swing.JLabel Splash_Title;
    private javax.swing.JPanel Stat;
    private javax.swing.JPanel Stat_Icon;
    private javax.swing.JPanel Stat_Status;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
